// Offline browser checks: production Firebase requests are blocked.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const out='docs/qa-incursions';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((q,r)=>{try{const u=new URL(q.url,'http://localhost'),f=u.pathname==='/font.otf'?process.env.QA_FONT:path.join(process.cwd(),u.pathname==='/'?'index.html':u.pathname);r.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.webp')?'image/webp':'application/octet-stream');r.end(fs.readFileSync(f));}catch{r.writeHead(404);r.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']});
try{
 const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.abort());
 async function font(){if(process.env.QA_FONT){await p.addStyleTag({content:"@font-face{font-family:QAJP;src:url('/font.otf')} :root{--f-body:QAJP;--f-display:QAJP;--f-mono:QAJP}body,button{font-family:QAJP}"});await p.evaluate(()=>document.fonts.load('16px QAJP'));}}
 async function shot(n){await p.locator('.toast').evaluateAll(es=>es.forEach(e=>e.hidden=true));await p.screenshot({path:out+'/'+n+'.jpg',quality:85,animations:'disabled'});}
 async function fresh(extra={}){await p.goto(origin);await p.evaluate(extra=>{const d=new Date();localStorage.setItem('shinso_gacha_state_v1',JSON.stringify({role:'agent',onboarded:true,currency:5000,pulls:120,lastTick:Date.now()+600000,levels:{},streak:{last:`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`,n:1},...extra}));},extra);await p.reload();await font();await p.evaluate(()=>{Math.random=()=>.5;});}
 async function open(){await p.locator('#incursion-status').click();assert(await p.locator('#incursion-dialog').isVisible());}
 async function draw(){await p.locator('[data-pull="1"]').click();await p.keyboard.press('Escape');}
 async function nextEvent(){await p.locator('[data-inc="close"]').first().click();await p.locator('.nav [data-nav="gacha"]').click();for(let i=0;i<5;i++)await draw();await open();}
 const state=()=>p.evaluate(()=>structuredClone(S.incursion));
 await fresh();assert(!(await p.locator('#incursion-status').isVisible()),'old save starts without retroactive danger');await p.locator('.nav [data-nav="gacha"]').click();for(let i=0;i<3;i++)await draw();assert.equal((await state()).level,36);assert.equal((await state()).event.kind,0);assert((await p.locator('.prop-photo').evaluate(e=>getComputedStyle(e).backgroundImage)).includes('station-after.webp'));await shot('noticed-390');await open();
 assert(await p.locator('[data-inc="identify"]').first().isDisabled());await p.locator('[data-inc="before"]').click();await p.locator('[data-inc="after"]').click();await p.locator('[data-inc="identify"][data-value="0"]').click();assert.equal((await state()).level,42);
 await p.reload();await font();await open();assert.equal((await state()).event.seen,3);assert(!(await p.locator('[data-inc="identify"]').first().isDisabled()));await shot('photo-390');await p.setViewportSize({width:320,height:568});await p.locator('[data-inc="identify"][data-value="1"]').scrollIntoViewIfNeeded();assert(await p.locator('[data-inc="identify"][data-value="1"]').isVisible());await shot('photo-320');await p.setViewportSize({width:390,height:844});
 // Tab stays within native modal; Escape closes only this dialog and restores focus.
 await p.keyboard.press('Tab');assert(await p.evaluate(()=>document.activeElement.closest('#incursion-dialog')!==null));await p.keyboard.press('Escape');assert.equal(await p.locator('#incursion-status').evaluate(e=>e===document.activeElement),true);await open();
 const money=await p.evaluate(()=>S.currency);await p.locator('[data-inc="identify"][data-value="1"]').click();assert.deepEqual(await p.evaluate(()=>[S.incursion.level,S.incursion.resolved,S.incursion.cooldown,S.currency]),[0,1,2,money]);await shot('calm-390');
 await nextEvent();assert.equal((await state()).event.kind,1);await p.locator('[data-inc="channel"][data-value="0"]').click();assert.equal((await state()).level,42);await p.locator('[data-inc="channel"][data-value="1"]').click();await shot('radio-390');await p.setViewportSize({width:320,height:568});await p.locator('[data-inc="disconnect"]').scrollIntoViewIfNeeded();await shot('radio-320');await p.setViewportSize({width:390,height:844});await p.reload();await font();await open();assert.equal((await state()).event.step,1);await p.locator('[data-inc="disconnect"]').click();assert.equal((await state()).resolved,2);
 await nextEvent();assert.equal((await state()).event.kind,2);await p.locator('[data-inc="seal"][data-value="2"]').click();assert.equal((await state()).event.step,0);await p.locator('[data-inc="seal"][data-value="0"]').click();await shot('seal-390');await p.reload();await font();await open();assert.equal((await state()).event.step,1);await p.locator('[data-inc="seal"][data-value="1"]').click();await p.locator('[data-inc="seal"][data-value="2"]').click();await p.evaluate(()=>incursionAction('seal',2));assert.equal((await state()).resolved,3,'completion cannot duplicate');
 // Cooling period protects exactly two new investigations.
 await p.locator('[data-inc="close"]').first().click();await p.locator('.nav [data-nav="gacha"]').click();await draw();await draw();assert.equal((await state()).level,0);await draw();assert.equal((await state()).level,12);
 // At 100, all new-opening routes stop before spending or awarding anything.
 await p.evaluate(()=>{S.incursion.level=100;S.incursion.event={kind:2,step:0,seen:0};S.freeDate='';markDirty();render();});await shot('breach-390');await p.locator('.nav [data-nav="home"]').click();assert.equal(await p.locator('.thread-radar').getAttribute('data-signal'),'close');assert.equal(await p.locator('#radar-distance').innerText(),'接近中');const primary=await p.locator('#agent-primary').boundingBox(),nav=await p.locator('.nav').boundingBox();assert(primary.y+primary.height<=nav.y,'danger status must not cover home CTA');await shot('home-intrusion-390');await p.locator('.nav [data-nav="gacha"]').click();const before=await p.evaluate(()=>({pt:S.currency,pulls:S.pulls,levels:totalLv(),free:S.freeDate}));await p.locator('[data-pull="1"]').click();assert(await p.locator('#incursion-dialog').isVisible());await p.evaluate(()=>{pull(100);freePull();});assert.deepEqual(await p.evaluate(()=>({pt:S.currency,pulls:S.pulls,levels:totalLv(),free:S.freeDate})),before);
 // Small/mobile/desktop bounds and controls, no forced timer or motion.
 for(const [width,height] of [[320,568],[390,844],[430,932],[1280,900]]){await p.setViewportSize({width,height});const box=await p.locator('#incursion-dialog').boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const b of await p.locator('.inc-seals button').all()){const r=await b.boundingBox();assert(r.height>=44&&r.width>=44);}await shot('seal-'+width);}
 await p.setViewportSize({width:390,height:844});await p.locator('.inc-details summary').click();await p.locator('[data-inc="quiet"]').check();assert(await p.locator('body.incursion-quiet').count());assert(!(await p.locator('.prop-photo').evaluate(e=>getComputedStyle(e).backgroundImage)).includes('station-after.webp'));await p.reload();await font();assert.equal((await state()).quiet,true);assert.equal((await state()).level,100,'reload does not worsen danger');
 // Live cloud never touched. Round-trip the extra state through the existing adapter.
 const saved=await p.evaluate(async()=>{let snapshot;cloud={canWrite:true,uid:'qa',saveRef:'users/qa',scoutRef:'scouts/qa',setDoc:async(ref,data)=>{if(ref==='users/qa')snapshot=data.state;}};FB={getCountFromServer:async()=>({data:()=>({count:0})}),collection:()=>({}),db:{}};markDirty();clearTimeout(flushT);await flush();FB.getDoc=async()=>({exists:()=>true,data:()=>({state:{...snapshot,incursion:{...snapshot.incursion,level:88},updatedAt:Date.now()+10000}})});await pullRemote();cloud.canWrite=false;return {saved:snapshot.incursion.level,restored:S.incursion.level,quiet:S.incursion.quiet,history:S.incursion.history.length};});assert.deepEqual(saved,{saved:100,restored:88,quiet:true,history:3});
 // Civilian play accumulates danger, but first three letters remain uninterrupted.
 await fresh({role:null,onboarded:false,pulls:0,lite:{lv:{},pulls:0}});await p.locator('#lite-pull').click();assert.equal(await p.evaluate(()=>S.incursion||null),null);await p.locator('[data-intro="skip"]').click();await p.evaluate(()=>{S.lite.event=null;renderLite();});await p.locator('#lite-pull').click();assert.equal((await state()).level,12);
 await p.evaluate(()=>{S.incursion.level=100;S.incursion.event={kind:2,step:0,seen:0};renderLite();});const civilian=await p.evaluate(()=>liteTotal());await p.evaluate(()=>litePull());assert.equal(await p.evaluate(()=>liteTotal()),civilian);assert(await p.locator('#incursion-dialog').isVisible());await p.locator('[data-inc="seal"][data-value="0"]').click();await p.locator('[data-inc="seal"][data-value="1"]').click();await p.locator('[data-inc="seal"][data-value="2"]').click();assert.equal((await state()).level,0);await p.locator('[data-inc="close"]').first().click();await p.evaluate(()=>litePull());assert.equal(await p.evaluate(()=>liteTotal()),civilian+1);
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({passed:true,checks:['old save migration without retroactive danger','real openings cause escalation','photo comparison and wrong answer','radio identification and disconnection','ordered sealing','progress resumes for all three actions','no duplicate completion or currency reward','two safe investigations after resolution','all new opening routes paused at 100 without loss','320/390/430/1280 dialog and 44px targets','keyboard modal focus + Escape return','quiet setting persists','no offline danger growth','Firebase adapter state round trip','civilian escalation and intro exemption'],cloud:'stub only',errors},null,2)+'\n');console.log('Incursion interaction checks passed');
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
