const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const out='docs/qa-incursions';const server=http.createServer((q,r)=>{try{const f=q.url==='/font.otf'?process.env.QA_FONT:path.join(process.cwd(),q.url==='/'?'index.html':q.url);r.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'application/octet-stream');r.end(fs.readFileSync(f));}catch{r.writeHead(404);r.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']});try{const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.abort());await p.goto('http://127.0.0.1:'+server.address().port);await p.evaluate(()=>{S.role='agent';S.onboarded=true;S.lite={intro:{done:true}};applyMode();});
async function font(){if(process.env.QA_FONT){await p.addStyleTag({content:"@font-face{font-family:QAJP;src:url('/font.otf')} :root{--f-body:QAJP;--f-display:QAJP;--f-mono:QAJP}body,button{font-family:QAJP}"});await p.evaluate(()=>document.fonts.load('16px QAJP'));}}
await font();
const setup=extra=>p.evaluate(extra=>{S.incursion={version:1,level:36,resolved:0,manual:0,samples:0,cooldown:0,history:[],event:{kind:2,tier:1,round:0,step:0,seen:0},...extra};markDirty();renderIncursion();},extra);
const state=()=>p.evaluate(()=>structuredClone(incursionState()));
// Real UI performs each sealing round; high tiers require more work and award once.
for(const tier of [1,2,3]){await setup({event:{kind:2,tier,round:0,step:0,seen:0}});await p.locator('#incursion-status').click();for(let round=0;round<tier;round++){for(let i=0;i<3;i++)await p.locator(`[data-inc="seal"][data-value="${i}"]`).click();if(round<tier-1){assert.equal((await state()).event.round,round+1);assert.equal((await state()).samples,0);}}
assert.equal((await state()).samples,tier);await p.evaluate(()=>incursionAction('seal',2));assert.equal((await state()).samples,tier);await p.locator('#incursion-dialog [data-inc="close"]').first().click();}
await setup({samples:2,event:null,level:0});await p.evaluate(()=>{go('lab');renderLab();});await p.locator('#incursion-defense summary').click();await p.locator('#incursion-defense [data-inc-up="guardian"]').click();assert.equal((await state()).defense.guardian,1);assert.equal((await state()).samples,0);assert(await p.locator('#incursion-defense [data-inc-up="guardian"]').isDisabled());
await p.evaluate(()=>{incursionInvestigate();incursionInvestigate();incursionInvestigate();});assert.equal((await state()).level,0);assert.equal((await state()).autoWait,6);assert.equal((await state()).samples,0);assert.equal((await state()).history.at(-1).auto,true);assert.equal((await state()).manual,0);
await p.evaluate(()=>{incursionInvestigate();incursionInvestigate();incursionInvestigate();incursionInvestigate();incursionInvestigate();});assert.equal((await state()).autoWait,1);assert((await state()).event);await p.evaluate(()=>incursionInvestigate());assert.equal((await state()).event,null);
await setup({defense:{guardian:2},event:{kind:2,tier:3,round:0},level:100});await p.evaluate(()=>incursionInvestigate());assert.equal((await state()).event.tier,3,'Lv3 cannot auto resolve');
await setup({defense:{guardian:2},autoEnabled:false,event:{kind:0,tier:1},level:36});await p.evaluate(()=>incursionInvestigate());assert((await state()).event,'toggle disables auto');
await setup({defense:{ward:3,recovery:3},event:null,level:0});await p.evaluate(()=>incursionInvestigate());assert.equal((await state()).level,7);await p.evaluate(()=>{S.incursion.event={kind:2,tier:1,round:0};incursionAction('seal',0);incursionAction('seal',1);incursionAction('seal',2);});assert.equal((await state()).cooldown,5);await p.evaluate(()=>{for(let i=0;i<5;i++)incursionInvestigate();});assert.equal((await state()).level,0);await p.evaluate(()=>incursionInvestigate());assert.equal((await state()).level,7);
const tiers=await p.evaluate(()=>[0,3,4,8,9,10,11].map(resolved=>incursionEvent({manual:resolved,resolved}).tier));assert.deepEqual(tiers,[1,2,1,3,1,2,3]);
// Save/reload preserves growth and cooldown without offline recovery or escalation.
await setup({samples:11,manual:8,resolved:8,defense:{ward:2,recovery:3,guardian:2},autoWait:4,cooldown:5,event:{kind:1,tier:3,round:1,step:1,seen:0}});await p.evaluate(()=>save());await p.reload();await font();assert.equal((await state()).samples,11);assert.equal((await state()).autoWait,4);assert.equal((await state()).cooldown,5);assert.equal((await state()).event.round,1);
await p.evaluate(()=>{go('lab');renderLab();});await p.locator('#incursion-defense summary').click();
for(const [width,height] of [[320,568],[390,844],[844,390]]){await p.setViewportSize({width,height});for(const btn of await p.locator('#incursion-defense button').all()){await btn.evaluate(e=>e.scrollIntoView({block:"center",behavior:"instant"}));assert(await btn.evaluate(e=>{const r=e.getBoundingClientRect(),t=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.height>=44&&(e===t||e.contains(t))&&e.scrollWidth<=e.clientWidth+1;}),`growth button obstructed at ${width}: ${await btn.textContent()}`);}assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#incursion-defense').scrollIntoViewIfNeeded();await p.screenshot({path:`${out}/growth-${width}.jpg`,quality:85});}
await p.setViewportSize({width:390,height:844});await p.locator('#incursion-status').click();await p.screenshot({path:`${out}/level3.jpg`,quality:85});assert.deepEqual(errors,[]);fs.writeFileSync(out+'/growth-results.json',JSON.stringify({passed:true,checks:['tier 1/2/3 rounds and one-time rewards','purchase and insufficient funds','automatic cooldown and no reward farming','Lv3 manual only','automation toggle','45% protection and five safe draws','unlock thresholds','saved growth and partial progress','320/390/844 layout and hit tests'],errors},null,2)+'\n');console.log('Incursion growth checks passed');
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
