// Hit-test actual controls with the danger bar active, including short landscape screens.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const out='docs/qa-incursions';fs.mkdirSync(out,{recursive:true});const server=http.createServer((q,r)=>{try{const u=new URL(q.url,'http://localhost'),f=u.pathname==='/font.otf'?process.env.QA_FONT:path.join(process.cwd(),u.pathname==='/'?'index.html':u.pathname);r.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'application/octet-stream');r.end(fs.readFileSync(f));}catch{r.writeHead(404);r.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']});try{const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.abort());
await p.addInitScript(()=>{if(localStorage.getItem('shinso_gacha_state_v1'))return;const d=new Date();localStorage.setItem('shinso_gacha_state_v1',JSON.stringify({role:'agent',onboarded:true,currency:5000,pulls:1000,levels:{u1:1},lastTick:Date.now()+600000,streak:{last:`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`,n:1},incursion:{version:1,level:100,resolved:0,cooldown:0,event:{kind:0,step:0,seen:3},history:[]}}));});
await p.goto('http://127.0.0.1:'+server.address().port);if(process.env.QA_FONT){await p.addStyleTag({content:"@font-face{font-family:QAJP;src:url('/font.otf')} :root{--f-body:QAJP;--f-display:QAJP;--f-mono:QAJP}body,button{font-family:QAJP}"});await p.evaluate(()=>document.fonts.load('16px QAJP'));}
async function hit(selector,label){const el=p.locator(selector).first();assert(await el.isVisible(),label+' visible');await el.evaluate(e=>e.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'}));const v=await el.evaluate(e=>{const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,t=document.elementFromPoint(x,y);return {hit:!!t&&(e===t||e.contains(t)),width:r.width,height:r.height,x:r.x,y:r.y,clipped:e.scrollWidth>e.clientWidth+1||e.scrollHeight>e.clientHeight+1,viewport:[innerWidth,innerHeight]};});assert(v.hit,label+' obstructed: '+JSON.stringify(v));assert(v.width>=44&&v.height>=44,label+' target too small: '+JSON.stringify(v));assert(!v.clipped,label+' text clipped: '+JSON.stringify(v));checks.push({label,...v});}
async function amountLine(){assert(await p.locator('#pt').evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);return r.getClientRects().length===1;}),'wallet amount must remain on one line');}
async function width(label){assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),label+' page overflow');}
for(const [widthPx,height] of [[320,568],[360,640],[390,844],[430,932],[844,390]]){
 await p.setViewportSize({width:widthPx,height});
 for(const view of ['home','gacha','archive','lab','report']){
  await p.locator(`.nav [data-nav="${view}"]`).click();await width(view);await hit('#incursion-status',view+' status '+widthPx);await hit('#wallet',view+' wallet '+widthPx);await amountLine();
  if(view==='home')await hit('#agent-primary','home CTA '+widthPx);
  if(view==='gacha')for(const n of [1,5,10,100])await hit(`[data-pull="${n}"]`,'draw '+n+' '+widthPx);
  if(view==='archive')await hit('[data-act="dossier"][data-id="u1"]','archive file '+widthPx);
  if(view==='lab')await hit('[data-act="upgrade"]','upgrade '+widthPx);
  if(view==='report'){await p.locator('[data-stab="report:settings"]').click();await hit('[data-spane="report:settings"] [data-intro="archive"]','settings replay '+widthPx);}
  for(const tab of ['home','gacha','archive','lab','report'])await hit(`.nav [data-nav="${tab}"]`,'nav '+tab+' '+widthPx);
 }
 for(const kind of [0,1,2]){await p.evaluate(k=>{S.incursion.event={kind:k,step:k===1?1:0,seen:3};openIncursion();},kind);await width('dialog '+kind);for(const selector of kind===0?['[data-inc="before"]','[data-inc="after"]','[data-inc="identify"][data-value="1"]']:kind===1?['[data-inc="channel"][data-value="1"]','[data-inc="disconnect"]']:['[data-inc="seal"][data-value="0"]','[data-inc="seal"][data-value="2"]'])await hit(selector,'dialog '+kind+' '+widthPx);await hit('#incursion-dialog [data-inc="close"]','dialog close '+widthPx);await p.locator('#incursion-dialog .inc-details summary').click();await p.locator('.inc-details label').evaluate(e=>e.scrollIntoView({block:'end',behavior:'instant'}));const closeRect=await p.locator('#incursion-dialog [data-inc="close"]').first().boundingBox();assert(closeRect.y>=0&&closeRect.y+closeRect.height<=height,'modal close remains visible while scrolled');await hit('.inc-details label','quiet checkbox label '+widthPx);await p.locator('#incursion-dialog [data-inc="close"]').first().click();}
 await p.evaluate(()=>{S.currency=9999999;render();});await hit('#wallet','large amount '+widthPx);await amountLine();await p.evaluate(()=>{S.currency=5000;render();});if(widthPx===320||widthPx===844){await p.locator('.nav [data-nav="home"]').click();await p.screenshot({path:out+'/layout-agent-'+widthPx+'.jpg',quality:85});}
}
// Civilian footer stays operable with the same header in portrait and landscape.
await p.evaluate(()=>{S.role=null;S.onboarded=false;S.pulls=0;S.lite={lv:{u1:3,u2:3},pulls:6,intro:{version:1,done:true}};applyMode();});
for(const [widthPx,height] of [[320,568],[390,844],[844,390]]){await p.setViewportSize({width:widthPx,height});await p.locator('[data-ltab="open"]').click();await width('civilian');await hit('#lite-pull','civilian CTA '+widthPx);await hit('#incursion-status','civilian status '+widthPx);for(const tab of ['open','files','notes']){await hit(`[data-ltab="${tab}"]`,'civilian nav '+tab+' '+widthPx);await p.locator(`[data-ltab="${tab}"]`).click();await width('civilian '+tab);}await p.locator('[data-ltab="open"]').click();await p.screenshot({path:out+'/layout-civilian-'+widthPx+'.jpg',quality:85});}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/layout-results.json',JSON.stringify({passed:true,checks,errors},null,2)+'\n');console.log('Layout hit checks passed: '+checks.length);
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
