const assert=require('node:assert/strict'),Layers=require('../assets/legend-layers-model'),Legend=require('../assets/legend-model');
const levels={u2:3},cases=Legend.CASES,profile=k=>({family:k%2?'device':'space'});
let s=Layers.normalize({},levels,cases);
assert.equal(Layers.status(s,'u2',levels,cases,{}, {},profile,{}).altered,false);
assert.equal(Layers.mark(s,'u2','noticed',false),false);
let v=Layers.status(s,'u2',levels,cases,{'dash:0':1},{},profile,{});
assert(v.altered&&!v.contradictions&&!v.chain);
assert.equal(Layers.mark(s,'u2','noticed',v.altered),true);
assert.equal(Layers.mark(s,'u2','noticed',v.altered),false);
v=Layers.status(s,'u2',levels,cases,{'dash:0':1},{},profile,{u2:true});
assert(v.contradictions);assert.equal(Layers.mark(s,'u2','compared',v.contradictions&&v.noticed),true);
v=Layers.status(s,'u2',levels,cases,{'dash:0':1},{1:true,3:true,5:true},profile,{u2:true});
assert(!v.chain,'unrelated evidence never reveals chain');
v=Layers.status(s,'u2',levels,cases,{'dash:0':1},{0:true,2:true,4:true},profile,{u2:true});
assert(v.chain&&v.related.length===3);
assert.equal(Layers.mark(s,'u2','linked',v.chain&&v.compared),true);
const restored=Layers.normalize(JSON.parse(JSON.stringify(s)),levels,cases);
assert.deepEqual(restored,s,'persisted flags survive reload');
assert.equal(Layers.status(restored,'u1',levels,cases,{}, {},profile,{}),null,'unowned case hidden');
assert(Layers.revised('u2',cases.u2).includes('追記'));
assert.equal(Layers.mark(restored,'u1','noticed',false),false);
assert.deepEqual(Layers.normalize({noticed:{u1:true,u2:true},compared:{u1:true},linked:{u1:true}},levels,cases).noticed,{u2:true});
console.log('Layer progression, ownership, three families, idempotence, migration passed');
